name: Continuous Integration Test

on: 
  push:
    branches:
      - master
    paths:
      - 'Web/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Repository Checkout
      uses: actions/checkout@v1
      
    - name: Hugo Setup
      uses: peaceiris/actions-hugo@v2.3.2
    
    - name: Hugo Build
      run: hugo --source $GITHUB_WORKSPACE/Web --destination $GITHUB_WORKSPACE/docs --cleanDestinationDir
    
    - name: Commit Files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automatic commit" -a    
    
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
