name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
      
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.2
    
    - name: Build
      run: hugo --source $GITHUB_WORKSPACE/Web --destination $GITHUB_WORKSPACE/docs --cleanDestinationDir
    
    - name: Commit Files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automatic commit" -a    
    
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
